# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'CategoryAll' do

  use_frameworks!

pod 'Alamofire', '~> 3.0.0'
pod 'SnapKit', '~> 0.19.1'
pod 'MJRefresh'
end
